In [1]:
%config Completer.use_jedi = False
%load_ext autoreload

# Imports and Functions

In [44]:
import pandas as pd
import csv
import numpy as np

# Import CSVs

In [193]:
df_publishers = pd.read_csv("../../data/ingest/game_data/first_publishers.csv").rename(columns={"id":"bgg_id"})
print(df_publishers.shape)
df_publishers.head()

(175041, 2)

   bgg_id                publisher
0       1            Hans im Glück
1       2  E. S. Lowe Company Inc.
2       3     Fantasy Flight Games
3       4                   KOSMOS
4       5                       3M

In [194]:
df_bgg = pd.read_csv("../../data/ingest/ranks/boardgame_ranks_20260319.csv", sep="|", escapechar="\\").rename(columns={"id":"bgg_id", "name":"bgg_name"})
print(df_bgg.shape)
df_bgg = df_bgg.merge(df_publishers, on="bgg_id", how="left")
df_bgg.head()

(175041, 17)

,bgg_id,bgg_name,yearpublished,rank,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank,queried_at_utc,publisher
0,224517,Brass: Birmingham,2018,1,8.39496,8.56730,57338,0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2026-03-19T20:38:04,Roxley
1,342942,Ark Nova,2021,2,8.35511,8.54201,59804,0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2026-03-19T20:38:04,Feuerland Spiele
2,161936,Pandemic Legacy: Season 1,2015,3,8.34782,8.50436,57147,0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,NaN,2026-03-19T20:38:04,Z-Man Games
3,174430,Gloomhaven,2017,4,8.30193,8.54303,66820,0,NaN,NaN,NaN,NaN,NaN,5.0,2.0,NaN,2026-03-19T20:38:04,Cephalofair Games
4,397598,Dune: Imperium – Uprising,2023,5,8.22545,8.70472,17374,0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,2026-03-19T20:38:04,Dire Wolf

In [136]:
df_paxtt = pd.read_csv("../../data/pax/title_corrections_raw.csv", sep="|", encoding="cp1252")
# for col in ["bgg_id", "game_id"]:
#     df_paxtt[col] = df_paxtt[col].astype(pd.Int64Dtype())
# df_paxtt = df_paxtt.drop(columns=["corrected_title", "corrected_bgg_id"])
df_paxtt["bgg_id"] = df_paxtt["bgg_id"].astype(pd.Int64Dtype())
df_paxtt.loc[df_paxtt["bgg_id"]==0, "bgg_id"] = np.nan
print(df_paxtt.shape)
df_paxtt.head()

(11418, 7)

,title,title_id,game_id,game_barcode,publisher_name,bgg_id,game_year
0,"""A Matter of Honor, Sire""",1148,2680,TTL1019O,AEG - DO NOT USE,<NA>,2014
1,#artbox,5025,10440,TTL06494I,Lavka Games,<NA>,2024
2,1 A.M. Jailbreak,5189,10805,25EAST0418,Saashi & Saashi,<NA>,2025
3,1 A.M. Jailbreak,5189,10806,25EAST0414,Saashi & Saashi,<NA>,2025
4,1 A.M. Jailbreak,5189,10807,25EAST0410,Saashi & Saashi,<NA>,2025

# Merge the data

## Manually fix bad bgg_ids

In [208]:
df_paxtt.loc[df_paxtt["bgg_id"]==89862, "bgg_id"] = 55253
df_paxtt.loc[df_paxtt["bgg_id"]==234497, "bgg_id"] = 242409
df_paxtt.loc[df_paxtt["bgg_id"]==268191, "bgg_id"] = 244271
df_paxtt.loc[df_paxtt["bgg_id"]==224965, "bgg_id"] = 72376
df_paxtt.loc[df_paxtt["bgg_id"]==63993, "bgg_id"] = 2290
df_paxtt.loc[df_paxtt["bgg_id"]==282031, "bgg_id"] = 364358

In [209]:
df_paxtt.loc[df_paxtt["title_id"]==387, "bgg_id"] = 224
df_paxtt.loc[df_paxtt["title_id"]==2443, "bgg_id"] = 224
df_paxtt.loc[df_paxtt["title_id"]==423, "bgg_id"] = 34010
df_paxtt.loc[df_paxtt["title_id"]==3830, "bgg_id"] = 324246
df_paxtt.loc[df_paxtt["title_id"]==1197, "bgg_id"] = 20437
df_paxtt.loc[df_paxtt["title_id"]==3601, "bgg_id"] = 20437

In [221]:
df_paxtt.loc[df_paxtt["title_id"]==1544, "bgg_id"] = 183231
df_paxtt.loc[df_paxtt["title_id"]==4311, "bgg_id"] = 357563
df_paxtt.loc[df_paxtt["title_id"]==4341, "bgg_id"] = 370391
df_paxtt.loc[df_paxtt["title_id"]==4146, "bgg_id"] = 359402
df_paxtt.loc[df_paxtt["title_id"]==992, "bgg_id"] = 12248
df_paxtt.loc[df_paxtt["title_id"]==3360, "bgg_id"] = 317983
df_paxtt.loc[df_paxtt["title_id"]==3858, "bgg_id"] = 317983
df_paxtt.loc[df_paxtt["title_id"]==5019, "bgg_id"] = 420214
df_paxtt.loc[df_paxtt["title_id"]==1912, "bgg_id"] = 207208
df_paxtt.loc[df_paxtt["title_id"]==5208, "bgg_id"] = 419454
df_paxtt.loc[df_paxtt["title_id"]==49, "bgg_id"] = 69789
df_paxtt.loc[df_paxtt["title_id"]==4649, "bgg_id"] = 348554
df_paxtt.loc[df_paxtt["title_id"]==2738, "bgg_id"] = 446
df_paxtt.loc[df_paxtt["title_id"]==60, "bgg_id"] = 10093
df_paxtt.loc[df_paxtt["title_id"]==5164, "bgg_id"] = 418354
df_paxtt.loc[df_paxtt["title_id"]==5038, "bgg_id"] = 418354
df_paxtt.loc[df_paxtt["title_id"]==66, "bgg_id"] = 43231
df_paxtt.loc[df_paxtt["title_id"]==73, "bgg_id"] = 551
df_paxtt.loc[df_paxtt["title_id"]==75, "bgg_id"] = 760
df_paxtt.loc[df_paxtt["title_id"]==5280, "bgg_id"] = 402674
df_paxtt.loc[df_paxtt["title_id"]==2023, "bgg_id"] = 2425
df_paxtt.loc[df_paxtt["title_id"]==5532, "bgg_id"] = 446748
df_paxtt.loc[df_paxtt["title_id"]==5192, "bgg_id"] = 424730
df_paxtt.loc[df_paxtt["title_id"]==5184, "bgg_id"] = 421310
df_paxtt.loc[df_paxtt["title_id"]==5216, "bgg_id"] = 420805
df_paxtt.loc[df_paxtt["title_id"]==4301, "bgg_id"] = 367891
df_paxtt.loc[df_paxtt["title_id"]==2146, "bgg_id"] = 231824
df_paxtt.loc[df_paxtt["title_id"]==4506, "bgg_id"] = 366994
df_paxtt.loc[df_paxtt["title_id"]==174, "bgg_id"] = 1294
df_paxtt.loc[df_paxtt["title_id"]==3693, "bgg_id"] = 329450
df_paxtt.loc[df_paxtt["title_id"]==1205, "bgg_id"] = 131121
df_paxtt.loc[df_paxtt["title_id"]==5403, "bgg_id"] = 395623
df_paxtt.loc[df_paxtt["title_id"]==2080, "bgg_id"] = 200058
df_paxtt.loc[df_paxtt["title_id"]==2503, "bgg_id"] = 316093
df_paxtt.loc[df_paxtt["title_id"]==3673, "bgg_id"] = 316093
df_paxtt.loc[df_paxtt["title_id"]==5122, "bgg_id"] = 400265
df_paxtt.loc[df_paxtt["title_id"]==4737, "bgg_id"] = 3076
df_paxtt.loc[df_paxtt["title_id"]==755, "bgg_id"] = 37196
df_paxtt.loc[df_paxtt["title_id"]==4422, "bgg_id"] = 147020
df_paxtt.loc[df_paxtt["title_id"]==3966, "bgg_id"] = 84876

In [ ]:
df_paxtt.loc[df_paxtt["title_id"]==5155, "bgg_id"] = 552
df_paxtt.loc[df_paxtt["title_id"]==3879, "bgg_id"] = 290236
df_paxtt.loc[df_paxtt["title_id"]==3269, "bgg_id"] = 170583
df_paxtt.loc[df_paxtt["title_id"]==148, "bgg_id"] = 65521
df_paxtt.loc[df_paxtt["title_id"]==167, "bgg_id"] = 478
df_paxtt.loc[df_paxtt["title_id"]==1857, "bgg_id"] = 478
df_paxtt.loc[df_paxtt["title_id"]==5497, "bgg_id"] = 205398
df_paxtt.loc[df_paxtt["title_id"]==2715, "bgg_id"] = 1294
df_paxtt.loc[df_paxtt["title_id"]==2720, "bgg_id"] = 1294
df_paxtt.loc[df_paxtt["title_id"]==1306, "bgg_id"] = 145639
df_paxtt.loc[df_paxtt["title_id"]==181, "bgg_id"] = 24742
df_paxtt.loc[df_paxtt["title_id"]==5135, "bgg_id"] = 394887
df_paxtt.loc[df_paxtt["title_id"]==1925, "bgg_id"] = 176306
df_paxtt.loc[df_paxtt["title_id"]==5239, "bgg_id"] = 424435
df_paxtt.loc[df_paxtt["title_id"]==5483, "bgg_id"] = 396895
df_paxtt.loc[df_paxtt["title_id"]==194, "bgg_id"] = 39463
df_paxtt.loc[df_paxtt["title_id"]==1093, "bgg_id"] = 121414
df_paxtt.loc[df_paxtt["title_id"]==1503, "bgg_id"] = 131357
df_paxtt.loc[df_paxtt["title_id"]==3857, "bgg_id"] = 317981
df_paxtt.loc[df_paxtt["title_id"]==2148, "bgg_id"] = 225694
df_paxtt.loc[df_paxtt["title_id"]==4582, "bgg_id"] = 376747
df_paxtt.loc[df_paxtt["title_id"]==4457, "bgg_id"] = 376747
df_paxtt.loc[df_paxtt["title_id"]==3803, "bgg_id"] = 317457
df_paxtt.loc[df_paxtt["title_id"]==241, "bgg_id"] = 6137
df_paxtt.loc[df_paxtt["title_id"]==243, "bgg_id"] = 121
df_paxtt.loc[df_paxtt["title_id"]==5041, "bgg_id"] = 181329
df_paxtt.loc[df_paxtt["title_id"]==5205, "bgg_id"] = 181329
df_paxtt.loc[df_paxtt["title_id"]==269, "bgg_id"] = 187
df_paxtt.loc[df_paxtt["title_id"]==269, "bgg_id"] = 72125
df_paxtt.loc[df_paxtt["title_id"]==283, "bgg_id"] = 33160
df_paxtt.loc[df_paxtt["title_id"]==3110, "bgg_id"] = 131121
df_paxtt.loc[df_paxtt["title_id"]==3588, "bgg_id"] = 329450
df_paxtt.loc[df_paxtt["title_id"]==5010, "bgg_id"] = 379
df_paxtt.loc[df_paxtt["title_id"]==4985, "bgg_id"] = 385761
df_paxtt.loc[df_paxtt["title_id"]==5042, "bgg_id"] = 439209
df_paxtt.loc[df_paxtt["title_id"]==300, "bgg_id"] = 40628
df_paxtt.loc[df_paxtt["title_id"]==4988, "bgg_id"] = 40628
df_paxtt.loc[df_paxtt["title_id"]==5298, "bgg_id"] = 419195
df_paxtt.loc[df_paxtt["title_id"]==5043, "bgg_id"] = 374024
df_paxtt.loc[df_paxtt["title_id"]==4329, "bgg_id"] = 376218
df_paxtt.loc[df_paxtt["title_id"]==5302, "bgg_id"] = 417518
df_paxtt.loc[df_paxtt["title_id"]==3368, "bgg_id"] = 275969

## Merge on bgg_id

In [222]:
df_m1 = df_paxtt.merge(df_bgg[["bgg_name", "bgg_id"]], on="bgg_id", how="inner")
df_m1.shape

(3947, 8)

In [223]:
df_m1.loc[df_m1["bgg_name"].notna()].head(10)

,title,title_id,game_id,game_barcode,publisher_name,bgg_id,game_year,bgg_name
0,12 Rivers,4341,9137,TTL32241I,Dofinn,370391,2022,12 Rivers
1,1920 Wall Street,1989,4259,TTL04221I,Looping Games,226255,2017,1920 Wall Street
2,1942 USS Yorktown,3378,7133,TTL06189I,Looping Games,279307,2019,1942 USS Yorktown
3,1942 USS Yorktown,3378,7134,TTL06193I,Looping Games,279307,2019,1942 USS Yorktown
4,1942 USS Yorktown,3378,7135,TTL06197I,Looping Games,279307,2019,1942 USS Yorktown
5,1987 Channel Tunnel,3379,7136,TTL06201I,Looping Games,279306,2019,1987 Channel Tunnel
6,1987 Channel Tunnel,3379,7137,TTL06209I,Looping Games,279306,2019,1987 Channel Tunnel
7,1987 Channel Tunnel,3379,7138,TTL06205I,Looping Games,279306,2019,1987 Channel Tunnel
8,3 Laws of Robotics,3324,6992,TTL06239I,Floodgate Games,271447,2019,3 Laws of Robotics
9,5-Minute Marvel,3191,6726,TTL09200I,Spin Master,253618,2019,5-Minute Marvel

# Merge on exact name, year, and publisher

In [236]:
df_m2 = df_paxtt.loc[~(df_paxtt["bgg_id"].isin(df_m1["bgg_id"])),['title', 'title_id', 'game_barcode', 'publisher_name', "game_year"]].drop_duplicates()
df_m2["title_lower"] = df_m2["title"].str.lower()
df_bgg["title_lower"] = df_bgg["bgg_name"].str.lower()
df_m2["publisher_lower"] = df_m2["publisher_name"].str.lower()
df_bgg["publisher_lower"] = df_bgg["publisher"].str.lower()
df_m2 = df_m2.merge(df_bgg[["bgg_id", "title_lower", "usersrated", "yearpublished", "publisher_lower"]], on=["title_lower", "publisher_lower"], how="inner")
df_m2 = df_m2.loc[df_m2["game_year"]+1>= df_m2["yearpublished"]]
df_m2 = df_m2.drop(columns=["title_lower", "publisher_lower"])
df_m2.shape

(2661, 8)

In [225]:
duplicated_bgg_id = df_m2[["title", "bgg_id"]].drop_duplicates()
duplicated_bgg_id = duplicated_bgg_id.loc[duplicated_bgg_id["bgg_id"].duplicated(), "bgg_id"].tolist()
len(duplicated_bgg_id)

23

In [215]:
df_m2.loc[df_m2["bgg_id"].isin(duplicated_bgg_id[5:10])]

,title,title_id,game_barcode,publisher_name,game_year,bgg_id,usersrated,yearpublished
568,Descent: Journeys in the Dark,216,NaN,Fantasy Flight Games,2014,17226,11874,2005
569,Descent: Journeys in the Dark,216,TTL100MT,Fantasy Flight Games,2014,17226,11874,2005
570,Descent: Journeys in the dark,217,TTL1011O,Fantasy Flight Games,2014,17226,11874,2005
602,Dogfight!: Rule The Skies in 20 Minutes!,4222,TTL16715I,Psc Games,2022,369154,390,2023
603,Dogfight!: Rule The Skies in 20 Minutes!,4222,TTL32344I,Psc Games,2023,369154,390,2023
604,Dogfight!: Rule The Skies in 20 Minutes!,4222,TTL32340I,Psc Games,2023,369154,390,2023
605,Dogfight!: Rule The Skies in 20 Minutes!,4222,TTL09972I,Psc Games,2023,369154,390,2023
606,Dogfight!: Rule The Skies in 20 Minutes!,4222,TTL09968I,Psc Games,2023,369154,390,2023
607,Dogfight!: Rule The Skies In 20 Minutes!,4761,TTL30343I,Psc Games,2024,369154,390,2023
939,Gift Of Tulips,4220,TTL16651I,Weird Giraffe Games,2022,286788,780,2022
940,Gift of Tulips,4382,TTL32435I,Weird Giraffe Games,2023,286788,780,2022
1118,Horrified: World Of Monsters,4882,24UNPL2176,Ravensburger,2024,423434,805,2024
1119,Horrified: World of Monsters,4883,24UNPL2167,Ravensburger,2024,423434,805,2024
1120,Horrified: World of Monsters,4883,24UNPL2180,Ravensburger,2024,423434,805,2024
1121,Horrified: World of Monsters,4883,24UNPL2091,Ravensburger,2024,423434,805,2024
1122,Horrified: World of Monsters,4883,24UNPL2163,Ravensburger,2024,423434,805,2024
1429,Middle-Earth Quest,519,TTL100JW,Fantasy Flight Games,2014,31563,4291,2009
1430,Middle-Earth Quest,519,TTL101BL,Fantasy Flight Games,2014,31563,4291,2009
1431,Middle-earth Quest,3156,TTL101BL,Fantasy Flight Games,2019,31563,4291,2009

In [226]:
duplicated_title = df_m2[["title", "bgg_id"]].drop_duplicates()
duplicated_title = duplicated_title.loc[duplicated_title["title"].duplicated(), "title"].tolist()
len(duplicated_title)

0

In [ ]:




df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000

In [227]:
# df_m2.loc[df_m2["title"].isin(duplicated_title[10:15])]

# Merge on name exact

In [256]:
df_m3 = df_paxtt.loc[~(df_paxtt["title_id"].isin(df_m1["title_id"].tolist() + df_m2["title_id"].tolist())),['title', 'title_id', 'game_barcode', 'publisher_name', "game_year"]].drop_duplicates()
df_m3["title_lower"] = df_m3["title"].str.lower()
df_bgg["title_lower"] = df_bgg["bgg_name"].str.lower()
df_m3 = df_m3.merge(df_bgg[["bgg_name", "bgg_id", "title_lower", "usersrated", "yearpublished", "publisher"]], on="title_lower", how="inner")
df_m3 = df_m3.loc[df_m3["game_year"]+1>= df_m3["yearpublished"]]
df_m3.shape

(3531, 11)

In [257]:
df_m3.head()

,title,title_id,game_barcode,publisher_name,game_year,title_lower,bgg_name,bgg_id,usersrated,yearpublished,publisher
0,"""A Matter of Honor, Sire""",1148,TTL1019O,AEG - DO NOT USE,2014,"""a matter of honor, sire""","""A Matter of Honor, Sire""",153128,22,2013,Against the Odds
1,10 days in asia,1,TTL100RV,Out of the Box,2014,10 days in asia,10 Days in Asia,22398,1204,2007,Out of the Box Publishing
2,1313 Dead End Drive,2053,TTL04115I,Parker Brothers,2017,1313 dead end drive,1313 Dead End Drive,4953,981,2002,Milton Bradley
3,1775: Rebellion,1946,TTL03505I,Academy Games,2017,1775: rebellion,1775: Rebellion,128996,4468,2013,"Academy Games, Inc."
4,1775: Rebellion,1946,TTL03505I,Academy Games,2018,1775: rebellion,1775: Rebellion,128996,4468,2013,"Academy Games, Inc."

In [258]:
duplicated_bgg_id = df_m3[["title", "bgg_id"]].drop_duplicates()
duplicated_bgg_id = duplicated_bgg_id.loc[duplicated_bgg_id["bgg_id"].duplicated(), "bgg_id"].tolist()
len(duplicated_bgg_id)

22

In [259]:
duplicated_title = df_m3[["title", "bgg_id"]].drop_duplicates()
duplicated_title = duplicated_title.loc[duplicated_title["title"].duplicated(), "title"].tolist()
len(duplicated_title)

244

In [261]:
df_m3.loc[df_m3["bgg_id"].isin(duplicated_bgg_id[0:10])]

,title,title_id,game_barcode,publisher_name,game_year,title_lower,bgg_name,bgg_id,usersrated,yearpublished,publisher
166,Ascension: Rise of Vigil,52,TTL02074I,Stoneblade Entertainment,2014,ascension: rise of vigil,Ascension: Rise of Vigil,138233,1823,2013,asmodee
167,Ascension: Rise of Vigil,52,TTL02078I,Stoneblade Entertainment,2014,ascension: rise of vigil,Ascension: Rise of Vigil,138233,1823,2013,asmodee
168,Ascension: Rise of Vigil,52,TTL101B7,Stoneblade Entertainment,2014,ascension: rise of vigil,Ascension: Rise of Vigil,138233,1823,2013,asmodee
169,Ascension: Rise Of Vigil,4211,TTL16658I,Capstone Games,2022,ascension: rise of vigil,Ascension: Rise of Vigil,138233,1823,2013,asmodee
170,Ascension: Storm of Souls,53,TTL1010V,Stoneblade Entertainment,2014,ascension: storm of souls,Ascension: Storm of Souls,108784,3704,2011,Stone Blade Entertainment
171,Ascension: Storm of Souls,53,TTL1012G,Stoneblade Entertainment,2014,ascension: storm of souls,Ascension: Storm of Souls,108784,3704,2011,Stone Blade Entertainment
172,Ascension: Storm of Souls,53,TTL02178I,Stoneblade Entertainment,2014,ascension: storm of souls,Ascension: Storm of Souls,108784,3704,2011,Stone Blade Entertainment
173,Ascension: Storm Of Souls,1747,TTL02178I,Gary Games,2017,ascension: storm of souls,Ascension: Storm of Souls,108784,3704,2011,Stone Blade Entertainment
179,Attack the Darkness,1100,TTL02179I,Protean Games,2014,attack the darkness,Attack the Darkness,131496,46,2013,(Self-Published)
180,Attack the Darkness,1100,TTL02172I,Protean Games,2014,attack the darkness,Attack the Darkness,131496,46,2013,(Self-Published)
181,Attack The Darkness,3167,TTL02179I,Protean Games,2019,attack the darkness,Attack the Darkness,131496,46,2013,(Self-Published)
182,Attack The Darkness,3167,TTL02172I,Protean Games,2019,attack the darkness,Attack the Darkness,131496,46,2013,(Self-Published)
299,Call of Yeti,5196,25EAST0445,Power9,2025,call of yeti,Call of Yeti,434136,32,2024,Power9 Games
300,Call Of Yeti,5197,25EAST0417,Power9,2025,call of yeti,Call of Yeti,434136,32,2024,Power9 Games
301,Call Of Yeti,5197,25EAST0413,Power9,2025,call of yeti,Call of Yeti,434136,32,2024,Power9 Games
394,Castles of Caladale,1663,TTL03208I,Renegade Game Studios,2017,castles of caladale,Castles of Caladale,213370,1020,2017,2 Pionki
395,Castles Of Caladale,3286,TTL09152I,Renegade Game Studiospax86392c,2019,castles of caladale,Castles of Caladale,213370,1020,2017,2 Pionki
497,Chutes and Ladders,166,NaN,Milton Bradley,2014,chutes and ladders,Chutes and Ladders,5432,5209,-200,(Public Domain)
498,Chutes And Ladders,2713,TTL05628I,Hasbro Gaming - DO NOT USE,2018,chutes and ladders,Chutes and Ladders,5432,5209,-200,(Public Domain)
499,Chutes And Ladders,2713,TTL05568I,Hasbro Gaming - DO NOT USE,2018,chutes and ladders,Chutes and Ladders,5432,5209,-200,(Public Domain)
1263,Gravwell: Escape from the 9th Dimension,1274,TTL02745I,Renegade Game Studios,2015,gravwell: escape from the 9th dimension,Gravwell: Escape from the 9th Dimension,142992,3765,2013,Cryptozoic Entertainment
1264,Gravwell: Escape From The 9th Dimension,3714,TTL05865I,Renegade Game Studios,2021,gravwell: escape from the 9th dimension,Gravwell: Escape from the 9th Dimension,142992,3765,2013,Cryptozoic Entertainment
1324,Hector and Achilles,371,TTL100XG,Mayfair Games,2014,hector and achilles,Hector and Achilles,8450,528,2003,Phalanx Games B.V.
1325,Hector And Achilles,3158,TTL100XG,Phalanx Games - DO NOT USE,2019,hector and achilles,Hector and Achilles,8450,528,2003,Phalanx Games B.V.
1326,Hector And Achilles,3685,TTL100XG,Phalanx,2021,hector and achilles,Hector and Achilles,8450,528,2003,Phalanx Games B.V.
1335,Hero: Tales of the Tomes,3997,TTL16677I,Jimmy Ellerth Entertainment Llc,2022,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1336,Hero: Tales of the Tomes,3997,TTL16673I,Jimmy Ellerth Entertainment Llc,2022,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1337,Hero: Tales of the Tomes,3997,TTL17478I,Jimmy Ellerth Entertainment Llc,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1338,Hero: Tales of the Tomes,3997,TTL17474I,Jimmy Ellerth Entertainment Llc,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1339,Hero: Tales of the Tomes,3997,TTL17470I,Jimmy Ellerth Entertainment Llc,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1340,Hero: Tales of the Tomes,3997,TTL34231I,Jimmy Ellerth Entertainment Llc,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1341,Hero: Tales of the Tomes,3997,TTL34245I,Jimmy Ellerth Entertainment Llc,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1342,Hero: Tales of the Tomes,3997,TTL34223I,Jimmy Ellerth Entertainment Llc,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1343,Hero: Tales Of The Tomes,4620,TTL09943I,Tomekeeper Entertainment,2023,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1344,Hero: Tales Of The Tomes,4620,24UNPL2843,Tomekeeper Entertainment,2024,hero: tales of the tomes,Hero: Tales of the Tomes,250808,89,2018,(Self-Published)
1514,Killer Bunnies and the Quest for the Magic Carrot,435,NaN,Pegasus Spiele,2014,killer bunnies and the quest for the magic carrot,Killer Bunnies and the Quest for the Magic Carrot,3699,6032,2002,Playroom Entertainment
1515,Killer Bunnies and the Quest for the Magic Carrot,435,TTL1004V,Pegasus Spiele,2014,killer bunnies and the quest for the magic carrot,Killer Bunnies and the Quest for the Magic Carrot,3699,6032,2002,Playroom Entertainment
1516,Killer Bunnies and the Quest for the Magic Carrot,435,TTL100H6,Pegasus Spiele,2014,killer bunnies and the quest for the magic carrot,Killer Bunnies and the Quest for the Magic Carrot,3699,6032,2002,Playroom Entertainment
1517,Killer Bunnies and the Quest for the Magic Carrot,435,TTL100KX,Pegasus Spiele,2014,killer bunnies and the quest for the magic carrot,Killer Bunnies and the Quest for the Magic Carrot,3699,6032,2002,Playroom Entertainment
1518,Killer Bunnies and the Quest for the Magic Carrot,435,TTL100ZQ,Pegasus Spiele,2014,killer bunnies and the quest for the magic carrot,Killer Bunnies and the Quest for the Magic Carrot,3699,6032,2002,Playroom Entertainment
1519,Killer Bunnies And The Quest For The Magic Carrot,3707,TTL09713I,Ultrapro Entertainment,2021,killer bunnies and the quest for the magic carrot,Killer Bunnies and the Quest for the Magic Carrot,3699,6032,2002,Playroom Entertainment

In [ ]:

df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000
df_paxtt.loc[df_paxtt["title_id"]==0000, "bgg_id"] = 0000

In [271]:
df_m3.loc[df_m3["title"].isin(duplicated_title[60:70])]

,title,title_id,game_barcode,publisher_name,game_year,title_lower,bgg_name,bgg_id,usersrated,yearpublished,publisher
1130,Food Fight,309,TTL100MN,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,99097,746,2011,Cryptozoic Entertainment
1131,Food Fight,309,TTL100MN,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,2193,70,1980,Tactical Studies Rules (TSR)
1132,Food Fight,309,TTL100MN,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,26781,0,2006,Avalon Games
1134,Food Fight,309,TTL100MO,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,99097,746,2011,Cryptozoic Entertainment
1135,Food Fight,309,TTL100MO,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,2193,70,1980,Tactical Studies Rules (TSR)
1136,Food Fight,309,TTL100MO,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,26781,0,2006,Avalon Games
1138,Food Fight,309,TTL100QK,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,99097,746,2011,Cryptozoic Entertainment
1139,Food Fight,309,TTL100QK,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,2193,70,1980,Tactical Studies Rules (TSR)
1140,Food Fight,309,TTL100QK,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,26781,0,2006,Avalon Games
1142,Food Fight,309,TTL100QO,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,99097,746,2011,Cryptozoic Entertainment
1143,Food Fight,309,TTL100QO,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,2193,70,1980,Tactical Studies Rules (TSR)
1144,Food Fight,309,TTL100QO,Cryptozoic- DO NOT USE,2014,food fight,Food Fight,26781,0,2006,Avalon Games
1167,Fruition,4363,TTL32347I,Buttonshy Games,2023,fruition,Fruition,374019,58,2022,Button Shy
1168,Fruition,4363,TTL32347I,Buttonshy Games,2023,fruition,Fruition,84883,0,2010,(Looking for a publisher)
1201,Gangster,332,NaN,Mayfair Games,2014,gangster,Gangster,31621,628,2007,AMIGO
1202,Gangster,332,NaN,Mayfair Games,2014,gangster,Gangster,25749,135,2006,LudoArt Verlag
1203,Gangster,332,NaN,Mayfair Games,2014,gangster,Gangster,24125,74,1994,"Éditions Gladius International, Inc."
1210,Get The Cheese!,1672,TTL04611I,Stronghold Games,2017,get the cheese!,Get The Cheese!,175634,246,2015,Japon Brand
1211,Get The Cheese!,1672,TTL04611I,Stronghold Games,2017,get the cheese!,Get the Cheese!,142230,1,2013,(Self-Published)
1254,Gold Fever,2852,TTL05780I,Stronghold Games,2019,gold fever,Gold Fever,234120,962,2017,Lautapelit.fi
1255,Gold Fever,2852,TTL05780I,Stronghold Games,2019,gold fever,Gold Fever,24364,2,1992,Anjar Co.
1288,Hamlet,4295,TTL32158I,Mighty Boards,2022,hamlet,Hamlet,64921,7,2015,(Web published)
1289,Hamlet,4295,TTL32158I,Mighty Boards,2022,hamlet,Hamlet,120894,0,2012,(Web published)
1291,Hamlet,4295,TTL32153I,Mighty Boards,2022,hamlet,Hamlet,64921,7,2015,(Web published)
1292,Hamlet,4295,TTL32153I,Mighty Boards,2022,hamlet,Hamlet,120894,0,2012,(Web published)
1294,Hamlet,4295,TTL32157I,Mighty Boards,2022,hamlet,Hamlet,64921,7,2015,(Web published)
1295,Hamlet,4295,TTL32157I,Mighty Boards,2022,hamlet,Hamlet,120894,0,2012,(Web published)
1361,High Society,5064,24UNPL2802,Reiner Knizia,2024,high society,High Society,220,16266,1995,Ravensburger
1362,High Society,5064,24UNPL2802,Reiner Knizia,2024,high society,High Society,327972,0,1963,"The House of James, Inc."
1421,Intarsia,4833,TTL32541I,Pegasus Spiele,2024,intarsia,Intarsia,422126,1297,2024,Deep Print Games
1422,Intarsia,4833,TTL32541I,Pegasus Spiele,2024,intarsia,Intarsia,43170,1,2008,Kadon Enterprises

Look for games with the same name but different bgg ids

In [99]:
len(duplicated_bgg_id)

62

In [89]:
df_m2[["bgg_id"]].drop_duplicates().shape

(3318, 1)

In [68]:
for k,v in df_m1.loc[(df_m1["bgg_name"].str.lower()!=df_m1["title"].str.lower())].iterrows():
    print(v.title, "|", v.bgg_name, "|",v.bgg_id, "|", v.game_id)

6 nimmt! | Beat the Heat | 432 | 2951
A Game of Thrones: Catan  Brotherhood of the Watch | A Game of Thrones: Catan – Brotherhood of the Watch | 229218 | 4344
A Game of Thrones: Catan  Brotherhood of the Watch | A Game of Thrones: Catan – Brotherhood of the Watch | 229218 | 4801
A Game of Thrones: Catan  Brotherhood of the Watch | A Game of Thrones: Catan – Brotherhood of the Watch | 229218 | 4780
Arkham Noir: Case #1  The Witch Cult Murders | Arkham Noir: Case #1 – The Witch Cult Murders | 225729 | 6331
Arkham Noir: Case #1  The Witch Cult Murders | Arkham Noir: Case #1 – The Witch Cult Murders | 225729 | 6332
Arkham Noir: Case #1  The Witch Cult Murders | Arkham Noir: Case #1 – The Witch Cult Murders | 225729 | 6333
Atelier: The Painter's Studio | Atelier | 311711 | 6932
Atelier: The Painter's Studio | Atelier | 311711 | 6963
Bloom in Blizzard | 花と吹雪 (Bloom in Blizzard) | 261431 | 6886
Cat Cafe | Cat Café | 279135 | 7319
Cat Cafe | Cat Café | 279135 | 7320
Cat Cafe | Cat Café | 279135 | 7321
Cat Cafe | Cat Café | 279135 | 7322
Cat Cafe | Cat Café | 279135 | 7323
Cat Cafe | Cat Café | 279135 | 7324
Cat Cafe | Cat Café | 279135 | 7325
Cat Cafe | Cat Café | 279135 | 7326
Cat Cafe | Cat Café | 279135 | 7327
Cat Cafe | Cat Café | 279135 | 7328
Cat Cafe | Cat Café | 279135 | 7329
Catan Histories: Settlers of America  Trails to Rails | Catan Histories: Settlers of America – Trails to Rails | 67239 | 6844
Chessplus: Pure Genius | Chessplus: Combine & Conquer | 245598 | 6296
Chessplus: Pure Genius | Chessplus: Combine & Conquer | 245598 | 6297
Chessplus: Pure Genius | Chessplus: Combine & Conquer | 245598 | 6298
Cities: Skylines  The Board Game | Cities: Skylines – The Board Game | 267370 | 7220
Cities: Skylines  The Board Game | Cities: Skylines – The Board Game | 267370 | 7224
Cities: Skylines  The Board Game | Cities: Skylines – The Board Game | 267370 | 7225
City of the Big Shoulders | City of the Big Shoulders: Burden of Destiny | 281722 | 6145
City of the Big Shoulders | City of the Big Shoulders: Burden of Destiny | 281722 | 6146
Confusion:  Espionage and Deception in the Cold War | Confusion: Espionage and Deception in the Cold War | 2961 | 1754
Confusion:  Espionage and Deception in the Cold War | Confusion: Espionage and Deception in the Cold War | 2961 | 1755
Darkest Night: Second Edition | Darkest Night | 128445 | 6208
Darkest Night: Second Edition | Darkest Night | 128445 | 6209
Darkest Night: Second Edition | Darkest Night | 128445 | 6210
Darkest Night: Second Edition | Darkest Night | 128445 | 6211
Descent: Journeys in the Dark (Second Edition | Descent: Journeys in the Dark (Second Edition) | 104162 | 3892
Dice Throne: Season Two  Gunslinger v. Samurai | Dice Throne: Season Two – Gunslinger v. Samurai | 266966 | 6119
Die Inseln im Nebel | Islands in the Mist | 285895 | 7280
Discoveries: The Journals of Lewis and Clark | Discoveries: The Journals of Lewis & Clark | 171669 | 6869
Eight-Minute Empire | Eight-Minute Empire: Legends | 142326 | 2993
Exploding Kittens: NSFW Deck | Exploding Kittens: NSFW Edition | 172242 | 7386
Extraordinary Adventures: Pirates | Extraordinary Adventures: Pirates! | 254994 | 6760
Extraordinary Adventures: Pirates | Extraordinary Adventures: Pirates! | 254994 | 6761
Extraordinary Adventures: Pirates | Extraordinary Adventures: Pirates! | 254994 | 6789
Extraordinary Adventures: Pirates | Extraordinary Adventures: Pirates! | 254994 | 6796
Five Tribes | Five Tribes: The Djinns of Naqala | 157354 | 5720
Fury of Dracula (Third/Fourth Edition) | The Fury of Dracula | 936 | 2997
Garbage Day! | Garbage Day | 179259 | 6556
Garbage Day! | Garbage Day | 179259 | 6557
Get Bit! Collectors Edition | Get Bit Trilogy Limited Edition | 159517 | 6538
Get Bit! Collectors Edition | Get Bit Trilogy Limited Edition | 159517 | 6859
Glux | Glüx | 207207 | 3677
Glux | Glüx | 207207 | 3678
Glux | Glüx | 207207 | 3679
Glux | Glüx | 207207 | 3680
Glux | Glüx | 207207 | 4203
Glux | Glüx | 207207 | 4204
Glux | Glüx | 207207 | 4206
Glux | Glüx | 207207 | 4208
Glux | Glüx | 207207 | 4405
Glux | Glüx | 207207 | 6841
Glux | Glüx | 207207 | 8537
Gobblet Gobblers | Gobblers | 13230 | 3860
Gugong | Gùgōng | 250458 | 5482
Gugong | Gùgōng | 250458 | 5483
I Say, Holmes! (Second Edition) | I Say, Holmes! | 34653 | 6291
I Say, Holmes! (Second Edition) | I Say, Holmes! | 34653 | 6292
Ilos | Ilôs | 219232 | 4300
Kauchuk | Rule the Realm | 274432 | 7248
Kauchuk | Rule the Realm | 274432 | 7249
Kauchuk | Rule the Realm | 274432 | 7250
Kauchuk | Rule the Realm | 274432 | 7717
Lagerstatten | Lagerstätten | 228882 | 4262
Magic: The Gathering  Heroes of Dominaria Board Game | Magic: The Gathering – Heroes of Dominaria Board Game | 248763 | 5320
Mesopotamia | Mesopotamia: Cradle of Civilization | 19301 | 6862
Nemo's War (Second Edition) | Nemo's War | 39232 | 5862
Nemo's War (Second Edition) | Nemo's War | 39232 | 6870
Nemo's War (Second Edition) | Nemo's War | 39232 | 6891
Okey Dokey | Level 10 | 211940 | 4021
On the Underground: London/Berlin | On the Underground | 24773 | 7218
On the Underground: London/Berlin | On the Underground | 24773 | 7219
On the Underground: London/Berlin | On the Underground | 24773 | 7221
Pandante | Pandánte | 140163 | 3071
Pandante | Pandánte | 140163 | 6603
Pandemic: Fall of Rome | Fall of Rome | 260428 | 4994
Pandemic: Fall of Rome | Fall of Rome | 260428 | 5415
Pandemic: Fall of Rome | Fall of Rome | 260428 | 5416
Pandemic: Reign of Cthulhu | Reign of Cthulhu | 192153 | 7034
Pandemic: Reign of Cthulhu | Reign of Cthulhu | 192153 | 7046
Pandemic: Reign of Cthulhu | Reign of Cthulhu | 192153 | 7047
Pass the Buck | Pass the Buck: A Game of Corporate Responsibility Management | 181647 | 3218
Penny Arcade: The Game  Gamers vs. Evil | Penny Arcade: The Game – Gamers vs. Evil | 97803 | 3062
Penny Arcade: The Game  Gamers vs. Evil | Penny Arcade: The Game – Gamers vs. Evil | 97803 | 3063
Pret-a-Porter | Prêt-à-Porter | 87890 | 7173
Pret-a-Porter | Prêt-à-Porter | 87890 | 7174
Pret-a-Porter | Prêt-à-Porter | 87890 | 7175
Q.E. | QE | 266830 | 7599
Q.E. | QE | 266830 | 7600
Q.E. | QE | 266830 | 7601
Q.E. | QE | 266830 | 7664
Rick and Morty: Anatomy Park  The Game | Rick and Morty: Anatomy Park – The Game | 220926 | 5354
Sagrada | Sagrada: 5-6 Player Expansion | 244262 | 7720
Schrodinger's Cats | Schrödinger's Cats | 172235 | 6044
Schrodinger's Cats | Schrödinger's Cats | 172235 | 6358
Schuttel's | Schüttel's | 234846 | 4932
Silver Bullet | Silver | 278553 | 6738
Silver Bullet | Silver | 278553 | 6739
SpyNet | Shadow Blades | 229006 | 6521
Stellar | Stellar Leap | 230570 | 7575
Stonehenge: An Anthology Board Game | Stonehenge | 183 | 308
Stonehenge: An Anthology Board Game | Stonehenge | 183 | 6838
Tannhauser | Tannhäuser | 25261 | 3066
Tannhauser | Tannhäuser | 25261 | 6616
Teen Titans GO! Deck-Building Game | DC Deck-Building Game: Teen Titans Go! | 221369 | 5361
Telestrations After Dark | Telestrations: After Dark | 173761 | 4903
The Quacks of Quedlinburg | Quacks | 244521 | 5228
The Quacks of Quedlinburg | Quacks | 244521 | 5430
The Quacks of Quedlinburg | Quacks | 244521 | 5765
The Red Dragon Inn: Allies  Spyke and Flower | The Red Dragon Inn: Allies – Spyke and Flower | 249578 | 5702
Ticket to Ride: First Journey (U.S. | Ticket to Ride: First Journey (U.S.) | 205125 | 4223
Tiny Epic Galaxies: Beyond the Black | Tiny Epic Galaxies | 163967 | 6753
Twilight of the Gods | Twilight of the Gods: Age of Revelation | 206904 | 6421
Twilight of the Gods | Twilight of the Gods: Age of Revelation | 206904 | 6422
Twilight of the Gods | Twilight of the Gods: Age of Revelation | 206904 | 6423
Twilight of the Gods | Twilight of the Gods: Age of Revelation | 206904 | 6424
Web of Spies | Spy Connection | 300148 | 6004
Wewlcome To... | Welcome To... | 233867 | 5656

Inspect list game_ids (Do not alter their names)
- 2951

In [55]:
df_m1.loc[(df_m1["name"].str.lower()!=df_m1["title"].str.lower())].head(50)

,title,title_id,game_id,game_barcode,publisher_name,bgg_id,name
13,6 nimmt!,1291,2951,TTL02693I,Mayfair Games,432,Beat the Heat
35,A Game of Thrones: Catan Brotherhood of the W...,2061,4344,TTL05177I,Fantasy Flight Games,229218,A Game of Thrones: Catan – Brotherhood of the ...
36,A Game of Thrones: Catan Brotherhood of the W...,2061,4801,TTL04365I,Fantasy Flight Games,229218,A Game of Thrones: Catan – Brotherhood of the ...
37,A Game of Thrones: Catan Brotherhood of the W...,2307,4780,TTL04321I,Fantasy Flight Games,229218,A Game of Thrones: Catan – Brotherhood of the ...
165,Arkham Noir: Case #1 The Witch Cult Murders,3026,6331,TTL03556I,Ludonova,225729,Arkham Noir: Case #1 – The Witch Cult Murders
166,Arkham Noir: Case #1 The Witch Cult Murders,3026,6332,TTL03560I,Ludonova,225729,Arkham Noir: Case #1 – The Witch Cult Murders
167,Arkham Noir: Case #1 The Witch Cult Murders,3026,6333,TTL03599I,Ludonova,225729,Arkham Noir: Case #1 – The Witch Cult Murders
172,Atelier: The Painter's Studio,3295,6932,TTL06016I,AEG,311711,Atelier
173,Atelier: The Painter's Studio,3295,6963,TTL06145I,AEG,311711,Atelier
304,Bloom in Blizzard,3275,6886,PAX86488C,Akihiroitoo,261431,花と吹雪 (Bloom in Blizzard)
453,Cat Cafe,3445,7319,TTL06304I,Mandoo Games,279135,Cat Café
454,Cat Cafe,3445,7320,TTL06305I,Mandoo Games,279135,Cat Café
455,Cat Cafe,3445,7321,TTL06281I,Mandoo Games,279135,Cat Café
456,Cat Cafe,3445,7322,TTL06300I,Mandoo Games,279135,Cat Café
457,Cat Cafe,3445,7323,TTL06297I,Mandoo Games,279135,Cat Café
458,Cat Cafe,3445,7324,TTL06301I,Mandoo Games,279135,Cat Café
459,Cat Cafe,3445,7325,TTL06293I,Mandoo Games,279135,Cat Café
460,Cat Cafe,3445,7326,TTL06309I,Mandoo Games,279135,Cat Café
461,Cat Cafe,3445,7327,TTL06289I,Mandoo Games,279135,Cat Café
462,Cat Cafe,3445,7328,TTL06285I,Mandoo Games,279135,Cat Café
463,Cat Cafe,3445,7329,TTL06313I,Mandoo Games,279135,Cat Café
494,Catan Histories: Settlers of America Trails t...,3254,6844,TTL02143I,Klaus Teuber,67239,Catan Histories: Settlers of America – Trails ...
522,Chessplus: Pure Genius,3018,6296,TTL05905I,Chess Plus,245598,Chessplus: Combine & Conquer
523,Chessplus: Pure Genius,3018,6297,TTL05901I,Chess Plus,245598,Chessplus: Combine & Conquer
524,Chessplus: Pure Genius,3018,6298,TTL05857I,Chess Plus,245598,Chessplus: Combine & Conquer
537,Cities: Skylines The Board Game,3406,7220,TTL06204I,Kosmos,267370,Cities: Skylines – The Board Game
538,Cities: Skylines The Board Game,3406,7224,TTL06167I,Kosmos,267370,Cities: Skylines – The Board Game
539,Cities: Skylines The Board Game,3406,7225,TTL06200I,Kosmos,267370,Cities: Skylines – The Board Game
541,City of the Big Shoulders,2982,6145,TTL10523I,Parallel,281722,City of the Big Shoulders: Burden of Destiny
542,City of the Big Shoulders,2982,6146,TTL10534I,Parallel,281722,City of the Big Shoulders: Burden of Destiny
607,Confusion: Espionage and Deception in the Col...,186,1754,TTL100WU,Stronghold Games,2961,Confusion: Espionage and Deception in the Cold...
608,Confusion: Espionage and Deception in the Col...,186,1755,TTL100WU,Stronghold Games,2961,Confusion: Espionage and Deception in the Cold...
719,Darkest Night: Second Edition,2994,6208,TTL03563I,Victory Point Games,128445,Darkest Night
720,Darkest Night: Second Edition,2994,6209,TTL03571I,Victory Point Games,128445,Darkest Night
721,Darkest Night: Second Edition,2994,6210,TTL03559I,Victory Point Games,128445,Darkest Night
722,Darkest Night: Second Edition,2994,6211,TTL03567I,Victory Point Games,128445,Darkest Night
762,Descent: Journeys in the Dark (Second Edition,1833,3892,TTL04878I,Fantasy Flight Games,104162,Descent: Journeys in the Dark (Second Edition)
786,Dice Throne: Season Two Gunslinger v. Samurai,2965,6119,TTL10503I,Roxley Games,266966,Dice Throne: Season Two – Gunslinger v. Samurai
787,Die Inseln im Nebel,3429,7280,TTL09247I,Schmidt Spiele,285895,Islands in the Mist
807,Discoveries: The Journals of Lewis and Clark,3266,6869,TTL04909I,Ludonaute,171669,Discoveries: The Journals of Lewis & Clark
963,Eight-Minute Empire,1316,2993,TTL02798I,Red Raven Games,142326,Eight-Minute Empire: Legends
1070,Exploding Kittens: NSFW Deck,3466,7386,TTL05104I,AdMagic Games,172242,Exploding Kittens: NSFW Edition
1074,Extraordinary Adventures: Pirates,3217,6760,TTL09075I,Forbidden Games,254994,Extraordinary Adventures: Pirates!
1075,Extraordinary Adventures: Pirates,3217,6761,TTL09071I,Forbidden Games,254994,Extraordinary Adventures: Pirates!
1076,Extraordinary Adventures: Pirates,3217,6789,TTL04899I,Forbidden Games,254994,Extraordinary Adventures: Pirates!
1077,Extraordinary Adventures: Pirates,3217,6796,TTL04895I,Forbidden Games,254994,Extraordinary Adventures: Pirates!
1158,Five Tribes,2787,5720,TTL05383I,Days of Wonder,157354,Five Tribes: The Djinns of Naqala
1288,Fury of Dracula (Third/Fourth Edition),1318,2997,TTL02751I,Fantasy Flight Games,936,The Fury of Dracula
1337,Garbage Day!,3124,6556,TTL09101I,Mayday Games,179259,Garbage Day
1338,Garbage Day!,3124,6557,TTL09097I,Mayday Games,179259,Garbage Day

In [ ]:
df_missing_1 = df_sheet.loc[~(df_sheet["name"].isin(df_m1["name"]))].copy()
df_missing_1.shape